import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer";
import UserContextProvider from "../Context/UserContext/UserContext";
import BackToTop from "../Components/BackToTop/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <div className=" background bg-black "></div>
          {/* <video src="/assets/video/video2.mp4" autoPlay muted className="opacity-35 absolute"></video> */}
          <Navbar />
          <div className="text-white">
            <BackToTop />

            {children}

            <Footer />
          </div>
        </body>
      </html>
    </UserContextProvider>
  );
}
