
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar/Navbar";
import Navigation from "../Components/Navbar/Navigation";
import Footer from "../Components/Footer/Footer";
import UserContextProvider from "../Context/UserContext/UserContext";
import BackToTop from "../Components/BackToTop/BackToTop";
import Loader from "@/Components/ui/RocketLoader";
import Layout from "@/Components/LoaderLayout/Layout"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <UserContextProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <Layout >
          <div className=" background bg-black "></div>
              <Navigation />
              <div className="text-white">
                <BackToTop />
                {children}
              </div>
              <Footer />
              </Layout>
        </body>
      </html>
    </UserContextProvider>
  );
}
